# Generated by Django 5.2.7 on 2025-10-21 19:19

from django.db import migrations


def seed_categories(apps, schema_editor):
    Category = apps.get_model('finances', 'Category')
    default_names = ['Продукти', 'Одяг', 'Інше']
    for name in default_names:
        Category.objects.get_or_create(name=name)


class Migration(migrations.Migration):
    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
    ]
